import { Course, User } from "./types/types";

export const performanceData = [
  { label: "A", value: 45, color: "#10b981" },
  { label: "B", value: 65, color: "#2b2bee" },
  { label: "C", value: 30, color: "#f59e0b" },
  { label: "D", value: 15, color: "#ef4444" },
];
export const enrollmentsTrendsData = [
  { month: "Jan", enrollments: 120 },
  { month: "Feb", enrollments: 200 },
  { month: "Mar", enrollments: 150 },
  { month: "Apr", enrollments: 300 },
  { month: "May", enrollments: 250 },
  { month: "Jun", enrollments: 400 },
  { month: "Jul", enrollments: 350 },
  { month: "Aug", enrollments: 450 },
  { month: "Sep", enrollments: 500 },
  { month: "Oct", enrollments: 600 },
  { month: "Nov", enrollments: 550 },
  { month: "Dec", enrollments: 700 },
];
export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Jenkins",
    email: "sarah.j@example.com",
    role: "admin",
    status: "active",
    lastLogin: "2 mins ago",
    avatar: "https://picsum.photos/id/64/100/100",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "m.chen@example.com",
    role: "manager",
    status: "active",
    lastLogin: "1 day ago",
    avatar: "https://picsum.photos/id/65/100/100",
  },
  {
    id: "3",
    name: "John Doe",
    email: "john.doe@university.edu",
    role: "manager",
    status: "pending",
    lastLogin: "Never",
  },
  {
    id: "4",
    name: "Emily Blunt",
    email: "emily.b@example.com",
    role: "manager",
    status: "inactive",
    lastLogin: "2 months ago",
  },
  {
    id: "5",
    name: "David Kim",
    email: "d.kim@tech.io",
    role: "manager",
    status: "active",
    lastLogin: "5 hours ago",
  },
  {
    id: "6",
    name: "John Doe",
    email: "john.doe@university.edu",
    role: "manager",
    status: "pending",
    lastLogin: "Never",
  },
  {
    id: "7",
    name: "Emily Blunt",
    email: "emily.b@example.com",
    role: "manager",
    status: "inactive",
    lastLogin: "2 months ago",
  },
  {
    id: "8",
    name: "David Kim",
    email: "d.kim@tech.io",
    role: "manager",
    status: "active",
    lastLogin: "5 hours ago",
  },
];

export const mockCourses: Partial<Course>[] = [
  {
    id: "1",
    title: "Advanced React Patterns",
    category: "Development",
    instructorIds: ["1"],
    status: "PUBLICADO",
    type: "ONLINE",
    studentsCount: 1204,
    duration: "4h 32m",
    thumbnail: "https://picsum.photos/id/180/800/450",
    description: "Master compound components, control props, and custom hooks.",
  },
  {
    id: "2",
    title: "UX Design Fundamentals",
    category: "Design",
    instructorIds: ["2"],
    status: "RASCUNHO",
    type: "HIBRIDO",
    studentsCount: 850,
    duration: "6h 15m",
    thumbnail: "https://picsum.photos/id/201/800/450",
    description: "Learn wireframing, prototyping, and user research basics.",
  },
  {
    id: "3",
    title: "SEO Strategy 2024",
    category: "Marketing",
    instructorIds: ["1"],
    status: "ENCERRADO",
    type: "PRESENCIAL",
    studentsCount: 2300,
    duration: "2h 10m",
    thumbnail: "https://picsum.photos/id/20/800/450",
    description: "Complete guide to technical SEO and content optimization.",
  },
];
